version: '3.8'

services:
  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: kmzen
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: bankdb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  bank-app:
    build: bank-app
    ports:
      - "8080:8080"
    depends_on:
      - mongo

volumes:
  mongo_data: